### ISSUE TITLE
Update libraries and verify the game runs on Marshmallow

### ISSUE THREAD

**Issue by Mknsri** [Mknsri/Drunk-Toss#1]
This project has not been updated for a while. An easy Hacktoberfest pull request can be made for updating the libraries used and  making sure the game still runs on the latest Android (Marshmallow)

**Comment by CleytonGoncalves** [comment]
It doesn't run on Android Studio and I don't have Eclipse around. I'm sorry, I should've noticed this.

**Comment by flekken** [comment]
I got it running on Android Studio, just import it as a gradle project. But if it is not maintained actively I do not see a reason to update the libraries. The game currently runs fine on Anroid Oreo.

**Comment by Mknsri** [comment]
I was 99% sure that it would have some problems running on new versions. I'll close the issue. Thanks for the help!
